Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
Traceback (most recent call last):
  File "recovery.py", line 188, in <module>
    list_of_couples=select_random_couples_from_list(list_of_couples,number_of_couple)
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 8557, in select_random_couples_from_list
    couple=list_of_couples[random.randint(0,len(list_of_couples)-1)]
  File "C:\Python27\lib\random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "C:\Python27\lib\random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,0, 0)
