Traceback (most recent call last):
  File "recovery_Diman_correct.py", line 524, in <module>
    my_draw(temp_graph_supply,'Demi0-%d-prune_one_hop'%(counter_isp))
  File "C:\Users\user\Novella\Backup Recovery n.34 - Codice Ottimizzato Last Version Server\Backup n.34\Backup n.34\my_lib.py", line 59, in my_draw
    graphDot=nx.to_pydot(H)
  File "C:\Python27\lib\site-packages\networkx\drawing\nx_pydot.py", line 202, in to_pydot
    p=pydot.Node(make_str(n),**str_nodedata)
  File "C:\Python27\lib\site-packages\pydot.py", line 676, in __init__
    self.create_attribute_methods(NODE_ATTRIBUTES)
  File "C:\Python27\lib\site-packages\pydot.py", line 599, in create_attribute_methods
    self.__setattr__( 'set_'+attr, lambda x, a=attr : self.obj_dict['attributes'].__setitem__(a, x) )
KeyboardInterrupt
Traceback (most recent call last):
  File "multiple_simulations_Diman_correct.py", line 127, in <module>
    os.system("python "+name_of_program_simulation +" "+str(seed_elem)+" "+str(alpha)+" "+str(prob_edge)+" "+str(num_simulations)+" "+str(i+1)+" "+distance_metric+" "+type_of_bet+" "+str(flow_fixed)+" "+str(flow_c)+" "+str(number_of_couple)+" "+str(fixed_distruption)+" "+str(var_distruption)+" "+filename_graph)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\Python27\lib\site-packages\matplotlib\_pylab_helpers.py", line 96, in destroy_all
    gc.collect(1)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "c:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "c:\Python27\lib\site-packages\matplotlib\_pylab_helpers.py", line 96, in destroy_all
    gc.collect(1)
KeyboardInterrupt
^C